### ISSUE TITLE
new_speak doesn't work when executing program on bot.py

### ISSUE THREAD

**Issue by UltimateNate** [UltimateNate/12-year-old-simulator#1]
It appears new_speak doesn't work if you execute it by running "python3 bot.py", but it works when executing by running "python3 new_speak.py"

When interacting it on IRC, and running it on bot.py, it crashes and outputs the following error message:

Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    import new_speak
  File "/home/nolsen/12-year-old-simulator/new_speak.py", line 20, in <module>
    import bot
  File "/home/nolsen/12-year-old-simulator/bot.py", line 266, in <module>
    select_speak_type()
  File "/home/nolsen/12-year-old-simulator/bot.py", line 101, in select_speak_type
    new_speak.speak()
AttributeError: module 'new_speak' has no attribute 'speak'

**Comment by GLolol** [comment]
The imports look like they don't work because `bot` and `new_speak` import each other recursively. You probably should split up the things in `bot` into parts public for plugins to use (and import that), and parts that are not.

**Comment by UltimateNate** [comment]
Bug has been fixed, thanks.
